use std::str::FromStr;
use crate::ast::{Header, Comment};
use lalrpop_util::ErrorRecovery;

// grammar<'err>(errors: &'err mut Vec<ErrorRecovery<usize, Token<'input>, &'static str>>);

grammar;

pub Header = {
    r"" <Comment>,
    "/*" <Comment>,
    <Comment> "*/",
    "//" <SingleComment>,
};

MultiLineComment: String = {
    r"[(?!/*)(?!*/)]+" => <>.to_string(),
    r"[^/\\*]+" => <>.to_string(),
}
